---
- name: Configure Ubuntu 18.04 VM (Local, Module-Driven)
  hosts: localhost
  connection: local
  become: true

  vars:
    network_interface: eth1
    ip_address: 192.168.0.150
    netmask: 255.255.255.0
    gateway: 192.168.0.171
    dns_server: 192.168.0.171
    repo_url: "https://github.com/jterry75/xrdp-init.git"
    share_path: "//192.168.0.171/git_repos"
    mount_point: "/mnt/windows_share"
    smb_user: "user"
    smb_password: "pass"
    marker_file: "{{ lookup('env','HOME') }}/.xrdp_installed"
    current_user: "{{ lookup('env','USER') }}"

  tasks:

    - name: Remove old eth1 netplan file
      file:
        path: /etc/netplan/60-eth1-static.yaml
        state: absent

    # -------------------------
    # Network Configuration
    # -------------------------
    - name: Configure both network adapters
      copy:
        dest: /etc/netplan/60-interfaces.yaml
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eth0:
                dhcp4: yes
              eth1:
                dhcp4: no
                addresses:
                  - 192.168.0.150/24
                gateway4: 192.168.0.171
                nameservers:
                  addresses: [192.168.0.171]
      notify: Apply netplan

    # -------------------------
    # Package Installation
    # -------------------------
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - openssh-server
          - linux-azure
          - linux-cloud-tools-generic
          - git
          - cifs-utils
          - xserver-xorg-core
          - xorg-video-abi-23
          - xorgxrdp
          - xrdp
        state: present

    - name: Remove unused packages
      apt:
        autoremove: yes
        purge: yes

    # -------------------------
    # XRDP Service and Certificates
    # -------------------------
    - name: Enable and start xrdp service
      systemd:
        name: xrdp
        enabled: yes
        state: started

    - name: Add user to ssl-cert group
      user:
        name: "{{ current_user }}"
        groups: ssl-cert
        append: yes

    - name: Ensure /etc/xrdp exists
      file:
        path: /etc/xrdp
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Remove old XRDP certs
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/xrdp/cert.pem
        - /etc/xrdp/key.pem

    - name: Generate self-signed XRDP certificate
      command: >
        openssl req -x509 -newkey rsa:2048
        -keyout /etc/xrdp/key.pem
        -out /etc/xrdp/cert.pem
        -days 3650
        -nodes
        -subj "/CN=localhost"
      args:
        creates: /etc/xrdp/cert.pem

    - name: Set permissions for XRDP certificates
      file:
        path: "{{ item.path }}"
        owner: xrdp
        group: xrdp
        mode: "{{ item.mode }}"
      loop:
        - { path: "/etc/xrdp/key.pem", mode: "0600" }
        - { path: "/etc/xrdp/cert.pem", mode: "0644" }

    - name: Restart XRDP service
      systemd:
        name: xrdp
        state: restarted

    # -------------------------
    # Mount Network Share
    # -------------------------
    - name: Ensure mount point exists
      file:
        path: "{{ mount_point }}"
        state: directory

    - name: Add CIFS mount to fstab
      mount:
        path: "{{ mount_point }}"
        src: "{{ share_path }}"
        fstype: cifs
        opts: "username={{ smb_user }},password={{ smb_password }},file_mode=0777,dir_mode=0777"
        state: mounted

  handlers:
    - name: Apply netplan
      command: netplan apply
